---
- name: Create Docker Build DIR
  file:
    path: "{{ workspace }}/ansible_managed_{{ env }}/k8s_related/{{ module }}"
    state: directory
    mode: '0755'

- name: Generate deployment file
  template:
    src: deployment_defination_file.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/k8s_related/{{ module }}/deployment_defination_file.yml"
#    trim_blocks: yes
- name: deploy deploy deploy
  shell:
    cmd: kubectl apply -f deployment_defination_file.yml
    chdir: "{{ workspace }}/ansible_managed_{{ env }}/k8s_related/{{ module }}/"

- name: Generate service file
  template:
    src: service.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/k8s_related/{{ module }}/service.yml"
#    trim_blocks: yes
- name: deploy deploy deploy
  shell:
    cmd: kubectl apply -f service.yml
    chdir: "{{ workspace }}/ansible_managed_{{ env }}/k8s_related/{{ module }}/"