---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name:  {{ env }}-{{ project_name }}-{{ module }}:latest
    namespace: {{ project_name }}
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: {{ env }}-{{ project_name }}-{{ module }}
        spec:
            containers:
                - name: {{ env }}-{{ project_name }}-{{ module }}
                  image: {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ env }}-{{ project_name }}-{{ module }}:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8181
