---
- name: Delete Unused Docker Objects
  docker_prune:
    containers: yes
    images: yes
    images_filters:
      dangling: false
    networks: yes
    volumes: yes
    builder_cache: yes
- name: ECR Login
  shell: "$(aws ecr get-login --region {{ aws_region }} --no-include-email)"
  args:
    executable: /bin/bash

- debug: var=code_commit_id.stdout_lines

- name: Create Docker Build DIR
  file:
    path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}"
    state: directory
    mode: '0755'

- name: Generate index file
  template:
    src: index.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}/index.htm"
#    trim_blocks: yes

- name: Generate Dockerfile
  template:
    src: docker-file.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}/Dockerfile"
#    trim_blocks: yes

- name: Generate Dockerfile
  template:
    src: webserver.j2
    dest: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}/webserver.py"
#    trim_blocks: yes

- name: Build Docker Image
  docker_image:
    build:
      path: "{{ workspace }}/ansible_managed_{{ env }}/docker_build/{{ module }}"
    name: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ env }}-{{ project_name }}-{{ module }}:local"
    push: no
    state: present
    source: build
  notify:
#    - Tag Image and Push to ECR [GIT COMMIT HASH]
    - Tag Image and Push to ECR [LATEST]
